/* Auto-generated by extract-collections.py – product data from JerseyBird */
window.SITE_COLLECTIONS = {
  "1984-salihlispor": {
    "title": "1984 SALIHLISPOR",
    "products": [
      {
        "handle": "1984-salihlispor-2024-home-jersey",
        "title": "1984 SALIHLISPOR 2024 HOME JERSEY",
        "price": "$49.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/sal3_540x.png?v=1726674090"
      },
      {
        "handle": "1984-salihlispor-2024-home-jersey-copy",
        "title": "1984 SALIHLISPOR 2024 AWAY JERSEY",
        "price": "$49.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/sal1_540x.png?v=1726673997"
      }
    ]
  },
  "al-qabila-fc": {
    "title": "AL QABILA FC",
    "products": [
      {
        "handle": "al-qabila-fc-2024-home-jersey-pre-order",
        "title": "AL QABILA FC 2024 HOME JERSEY",
        "price": "$74.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/aq2_540x.png?v=1733416821"
      }
    ]
  },
  "bowleys-athletic-club": {
    "title": "BOWLEY'S ATHLETIC CLUB",
    "products": [
      {
        "handle": "bowleys-athletic-club-2024-2025-home-shirt",
        "title": "BOWLEYS ATHLETIC CLUB 2024 HOME SHIRT",
        "price": "$59.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/bowleynew_540x.png?v=1726946402"
      }
    ]
  },
  "cuenca-jrs": {
    "title": "CUENCA JRS",
    "products": [
      {
        "handle": "cuenca-jrs-2025-third-shirt",
        "title": "CUENCA JRS 2025 THIRD SHIRT",
        "price": "$29.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/CuencaThird_540x.png?v=1742407994"
      },
      {
        "handle": "cuenca-jrs-2025-away-shirt",
        "title": "CUENCA JRS 2025 AWAY SHIRT",
        "price": "$29.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/CuencaAway_540x.png?v=1742407934"
      },
      {
        "handle": "cuenca-jrs-2025-home-shirt",
        "title": "CUENCA JRS 2025 HOME SHIRT",
        "price": "$29.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/CuencaHome_540x.png?v=1742407829"
      },
      {
        "handle": "cuenca-jrs-2024-inaugural-season-shirt-preorder-rest-of-world",
        "title": "CUENCA JRS 2024 INAUGURAL SEASON SHIRT",
        "price": "$34.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/cuencaprod1_540x.png?v=1733768301"
      }
    ]
  },
  "jerseybird-night-2025": {
    "title": "JERSEYBIRD NIGHT 2025",
    "products": [
      {
        "handle": "jerseybird-night-2025-preorder",
        "title": "JERSEYBIRD NIGHT 2025 SHIRT",
        "price": "$19.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/SnapInsta.to_538799330_18108810967550393_1952092634321779792_n_540x.jpg?v=1770642911"
      },
      {
        "handle": "jerseybird-night-printers-alley-jersey-pre-order",
        "title": "JERSEYBIRD NIGHT 2024 PRINTER'S ALLEY JERSEY",
        "price": "$19.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/jn9_540x.png?v=1724440330"
      },
      {
        "handle": "herrera-fc-2024-home-jersey-pre-order-copy",
        "title": "JERSEYBIRD NIGHT 2024 HISPANIC HERITAGE JERSEY",
        "price": "$19.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/jn8_04ee12dd-3b63-4b19-9d4f-765cb9510c9b_540x.png?v=1724440295"
      }
    ]
  },
  "herrera-fc": {
    "title": "HERRERA FC",
    "products": [
      {
        "handle": "herrera-fc-2024-home-keeper-jersey-pre-order",
        "title": "HERRERA FC 2024 HOME KEEPER JERSEY",
        "price": "$49.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/blackfront_540x.png?v=1724953390"
      },
      {
        "handle": "herrera-fc-2024-away-jersey",
        "title": "HERRERA FC 2024 AWAY JERSEY",
        "price": "$49.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/hfront_540x.png?v=1724951198"
      },
      {
        "handle": "herrera-fc-2024-home-jersey",
        "title": "HERRERA FC 2024 HOME JERSEY",
        "price": "$49.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/HERRERAPRODUCTCOVER_540x.png?v=1724949882"
      },
      {
        "handle": "herrera-fc-2024-away-keeper-jersey-pre-order",
        "title": "HERRERA FC 2024 AWAY KEEPER JERSEY",
        "price": "$49.95",
        "soldOut": true,
        "image": "https://jerseybird.com/cdn/shop/files/orangefront_540x.png?v=1724953108"
      }
    ]
  },
  "kahawa-pride-fc": {
    "title": "KAHAWA PRIDE FC",
    "products": [
      {
        "handle": "kahawa-pride-fc-2024-home-jersey",
        "title": "KAHAWA PRIDE FC 2024 HOME JERSEY",
        "price": "$49.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/kc1_540x.png?v=1726502845"
      },
      {
        "handle": "kahawa-pride-fc-oversize-fleeced-hoodie",
        "title": "Kahawa Pride FC Oversize Fleeced Hoodie",
        "price": "$35.82",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/e4ffb565fc6f4139b8cafb6808d516c5_540x.png?v=1769037761"
      },
      {
        "handle": "performance-t-shirt-1",
        "title": "Kahawa Pride FC Performance T-shirt",
        "price": "$29.94",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/60fc4a98031f446a8c218a45c880251a_540x.png?v=1740611779"
      },
      {
        "handle": "kahawa-pride-fc-ksa-preseason-cup-champions-shirt",
        "title": "KAHAWA PRIDE FC KSA PRESEASON CUP CHAMPIONS SHIRT",
        "price": "$29.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/84d82191df6d403ebbc3519a9aabcbe5_989216b8-37a6-4ddd-ad79-35e0167675ce_540x.png?v=1762031406"
      },
      {
        "handle": "kahawa-pride-fc-2024-home-keeper-jersey",
        "title": "KAHAWA PRIDE FC 2024 HOME KEEPER JERSEY",
        "price": "$49.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/KahawaKeeper1_540x.png?v=1769265670"
      },
      {
        "handle": "kahawa-pride-fc-dark-training-jersey",
        "title": "KAHAWA PRIDE FC DARK TRAINING JERSEY",
        "price": "$36.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/Dark_540x.png?v=1776462243"
      },
      {
        "handle": "kahawa-pride-fc-light-training-jersey",
        "title": "KAHAWA PRIDE FC LIGHT TRAINING JERSEY",
        "price": "$36.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/Light_540x.png?v=1776462208"
      }
    ]
  },
  "philippines-national-team": {
    "title": "2023/2024 PHILIPPINES NATIONAL TEAM JERSEYS",
    "products": [
      {
        "handle": "philippines-national-team-2023-2024-home-kit",
        "title": "PHILIPPINES NATIONAL TEAM 2023/2024 HOME SHIRT",
        "price": "$74.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/PHEDIT1_540x.png?v=1700088823"
      },
      {
        "handle": "philippines-national-team-2023-2024-away-kit",
        "title": "PHILIPPINES NATIONAL TEAM 2023/2024 AWAY SHIRT",
        "price": "$74.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/phaway1_540x.png?v=1701721919"
      }
    ]
  },
  "walton-hersham-fc": {
    "title": "WALTON & HERSHAM FC",
    "products": [
      {
        "handle": "walton-hersham-fc-2025-away-shirt",
        "title": "WALTON & HERSHAM FC 2025 AWAY SHIRT",
        "price": "$58.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/Screenshot2025-07-02at10.46.15_540x.webp?v=1770642862"
      },
      {
        "handle": "walton-hersham-2025-home-shirt",
        "title": "WALTON & HERSHAM FC 2025 HOME SHIRT",
        "price": "$58.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/Screenshot_2025-07-01_at_14.42.36_814af6ee-b7b2-4174-8d68-9c6ec1167b51_540x.webp?v=1770642841"
      }
    ]
  },
  "jerseybird-apparel": {
    "title": "JERSEYBIRD APPAREL",
    "products": [
      {
        "handle": "jerseybird-global-migration-hoodie",
        "title": "JERSEYBIRD 1 OF 40 \"GLOBAL MIGRATION\" HOODIE",
        "price": "$74.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/CopyofUntitled-2_540x.jpg?v=1705605641"
      },
      {
        "handle": "jerseybird-premium-logo-t-shirt",
        "title": "JERSEYBIRD PREMIUM LOGO TEE",
        "price": "$38.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/Pf1_540x.png?v=1688140494"
      },
      {
        "handle": "jerseybird-premium-logo-tee-3-copy",
        "title": "JERSEYBIRD PREMIUM LOGO TEE",
        "price": "$38.95",
        "soldOut": false,
        "image": "https://jerseybird.com/cdn/shop/files/Pf2_fa147e91-7045-4587-a2d9-c71811a67749_540x.png?v=1700089633"
      }
    ]
  }
};

window.SITE_PRODUCT_PAGES = {
  "fcb-magpies": {
    "title": "FCB MAGPIES 2024 SPECIAL SHIRT",
    "collection": "fcb-magpies",
    "price": "$59.95",
    "soldOut": false,
    "image": "https://jerseybird.com/cdn/shop/files/GIBNEW1_540x.png?v=1733412308",
    "description": "Where should we send it?"
  },
  "vv-vianen": {
    "title": "VV VIANEN 2024 SPECIAL SHIRT",
    "collection": "vv-vianen",
    "price": "$29.95",
    "soldOut": false,
    "image": "https://jerseybird.com/cdn/shop/files/VV1_540x.png?v=1725044369",
    "description": "Where should we send it?"
  }
};
