/* Auto-extracted from JerseyBird */
const CURRENCIES = [
  { code: 'AL', flag: 'al', label: 'Albania (ALL L)' },
  { code: 'DZ', flag: 'dz', label: 'Algeria (DZD د.ج)' },
  { code: 'AD', flag: 'ad', label: 'Andorra (EUR €)' },
  { code: 'AO', flag: 'ao', label: 'Angola (USD $)' },
  { code: 'AI', flag: 'ai', label: 'Anguilla (XCD $)' },
  { code: 'AG', flag: 'ag', label: 'Antigua & Barbuda (XCD $)' },
  { code: 'AR', flag: 'ar', label: 'Argentina (USD $)' },
  { code: 'AM', flag: 'am', label: 'Armenia (AMD դր.)' },
  { code: 'AW', flag: 'aw', label: 'Aruba (AWG ƒ)' },
  { code: 'AU', flag: 'au', label: 'Australia (AUD $)' },
  { code: 'AT', flag: 'at', label: 'Austria (EUR €)' },
  { code: 'AZ', flag: 'az', label: 'Azerbaijan (AZN ₼)' },
  { code: 'BS', flag: 'bs', label: 'Bahamas (BSD $)' },
  { code: 'BH', flag: 'bh', label: 'Bahrain (USD $)' },
  { code: 'BD', flag: 'bd', label: 'Bangladesh (BDT ৳)' },
  { code: 'BB', flag: 'bb', label: 'Barbados (BBD $)' },
  { code: 'BE', flag: 'be', label: 'Belgium (EUR €)' },
  { code: 'BZ', flag: 'bz', label: 'Belize (BZD $)' },
  { code: 'BJ', flag: 'bj', label: 'Benin (XOF Fr)' },
  { code: 'BM', flag: 'bm', label: 'Bermuda (USD $)' },
  { code: 'BO', flag: 'bo', label: 'Bolivia (BOB Bs.)' },
  { code: 'BA', flag: 'ba', label: 'Bosnia & Herzegovina (BAM КМ)' },
  { code: 'BW', flag: 'bw', label: 'Botswana (BWP P)' },
  { code: 'BR', flag: 'br', label: 'Brazil (USD $)' },
  { code: 'VG', flag: 'vg', label: 'British Virgin Islands (USD $)' },
  { code: 'BN', flag: 'bn', label: 'Brunei (BND $)' },
  { code: 'BG', flag: 'bg', label: 'Bulgaria (EUR €)' },
  { code: 'BF', flag: 'bf', label: 'Burkina Faso (XOF Fr)' },
  { code: 'BI', flag: 'bi', label: 'Burundi (BIF Fr)' },
  { code: 'KH', flag: 'kh', label: 'Cambodia (KHR ៛)' },
  { code: 'CM', flag: 'cm', label: 'Cameroon (XAF CFA)' },
  { code: 'CA', flag: 'ca', label: 'Canada (CAD $)' },
  { code: 'CV', flag: 'cv', label: 'Cape Verde (CVE $)' },
  { code: 'BQ', flag: 'bq', label: 'Caribbean Netherlands (USD $)' },
  { code: 'KY', flag: 'ky', label: 'Cayman Islands (KYD $)' },
  { code: 'TD', flag: 'td', label: 'Chad (XAF CFA)' },
  { code: 'CL', flag: 'cl', label: 'Chile (USD $)' },
  { code: 'CN', flag: 'cn', label: 'China (CNY ¥)' },
  { code: 'CO', flag: 'co', label: 'Colombia (USD $)' },
  { code: 'KM', flag: 'km', label: 'Comoros (KMF Fr)' },
  { code: 'CK', flag: 'ck', label: 'Cook Islands (NZD $)' },
  { code: 'CR', flag: 'cr', label: 'Costa Rica (CRC ₡)' },
  { code: 'HR', flag: 'hr', label: 'Croatia (EUR €)' },
  { code: 'CW', flag: 'cw', label: 'Curaçao (ANG ƒ)' },
  { code: 'CY', flag: 'cy', label: 'Cyprus (EUR €)' },
  { code: 'CZ', flag: 'cz', label: 'Czechia (CZK Kč)' },
  { code: 'DK', flag: 'dk', label: 'Denmark (DKK kr.)' },
  { code: 'DJ', flag: 'dj', label: 'Djibouti (DJF Fdj)' },
  { code: 'DM', flag: 'dm', label: 'Dominica (XCD $)' },
  { code: 'DO', flag: 'do', label: 'Dominican Republic (DOP $)' },
  { code: 'EC', flag: 'ec', label: 'Ecuador (USD $)' },
  { code: 'EG', flag: 'eg', label: 'Egypt (EGP ج.م)' },
  { code: 'SV', flag: 'sv', label: 'El Salvador (USD $)' },
  { code: 'GQ', flag: 'gq', label: 'Equatorial Guinea (XAF CFA)' },
  { code: 'EE', flag: 'ee', label: 'Estonia (EUR €)' },
  { code: 'SZ', flag: 'sz', label: 'Eswatini (USD $)' },
  { code: 'ET', flag: 'et', label: 'Ethiopia (ETB Br)' },
  { code: 'FK', flag: 'fk', label: 'Falkland Islands (FKP £)' },
  { code: 'FO', flag: 'fo', label: 'Faroe Islands (DKK kr.)' },
  { code: 'FJ', flag: 'fj', label: 'Fiji (FJD $)' },
  { code: 'FI', flag: 'fi', label: 'Finland (EUR €)' },
  { code: 'FR', flag: 'fr', label: 'France (EUR €)' },
  { code: 'GF', flag: 'gf', label: 'French Guiana (EUR €)' },
  { code: 'PF', flag: 'pf', label: 'French Polynesia (XPF Fr)' },
  { code: 'GA', flag: 'ga', label: 'Gabon (XOF Fr)' },
  { code: 'GM', flag: 'gm', label: 'Gambia (GMD D)' },
  { code: 'GE', flag: 'ge', label: 'Georgia (USD $)' },
  { code: 'DE', flag: 'de', label: 'Germany (EUR €)' },
  { code: 'GH', flag: 'gh', label: 'Ghana (USD $)' },
  { code: 'GI', flag: 'gi', label: 'Gibraltar (GBP £)' },
  { code: 'GR', flag: 'gr', label: 'Greece (EUR €)' },
  { code: 'GL', flag: 'gl', label: 'Greenland (DKK kr.)' },
  { code: 'GD', flag: 'gd', label: 'Grenada (XCD $)' },
  { code: 'GP', flag: 'gp', label: 'Guadeloupe (EUR €)' },
  { code: 'GT', flag: 'gt', label: 'Guatemala (GTQ Q)' },
  { code: 'GG', flag: 'gg', label: 'Guernsey (GBP £)' },
  { code: 'GN', flag: 'gn', label: 'Guinea (GNF Fr)' },
  { code: 'GW', flag: 'gw', label: 'Guinea-Bissau (XOF Fr)' },
  { code: 'GY', flag: 'gy', label: 'Guyana (GYD $)' },
  { code: 'HT', flag: 'ht', label: 'Haiti (USD $)' },
  { code: 'HN', flag: 'hn', label: 'Honduras (HNL L)' },
  { code: 'HK', flag: 'hk', label: 'Hong Kong SAR (HKD $)' },
  { code: 'HU', flag: 'hu', label: 'Hungary (HUF Ft)' },
  { code: 'IS', flag: 'is', label: 'Iceland (ISK kr)' },
  { code: 'IN', flag: 'in', label: 'India (INR ₹)' },
  { code: 'ID', flag: 'id', label: 'Indonesia (IDR Rp)' },
  { code: 'IE', flag: 'ie', label: 'Ireland (EUR €)' },
  { code: 'IL', flag: 'il', label: 'Israel (ILS ₪)' },
  { code: 'IT', flag: 'it', label: 'Italy (EUR €)' },
  { code: 'JM', flag: 'jm', label: 'Jamaica (JMD $)' },
  { code: 'JP', flag: 'jp', label: 'Japan (JPY ¥)' },
  { code: 'JE', flag: 'je', label: 'Jersey (USD $)' },
  { code: 'JO', flag: 'jo', label: 'Jordan (USD $)' },
  { code: 'KZ', flag: 'kz', label: 'Kazakhstan (KZT ₸)' },
  { code: 'KE', flag: 'ke', label: 'Kenya (KES KSh)' },
  { code: 'KI', flag: 'ki', label: 'Kiribati (USD $)' },
  { code: 'KW', flag: 'kw', label: 'Kuwait (USD $)' },
  { code: 'KG', flag: 'kg', label: 'Kyrgyzstan (KGS som)' },
  { code: 'LA', flag: 'la', label: 'Laos (LAK ₭)' },
  { code: 'LV', flag: 'lv', label: 'Latvia (EUR €)' },
  { code: 'LS', flag: 'ls', label: 'Lesotho (USD $)' },
  { code: 'LI', flag: 'li', label: 'Liechtenstein (CHF CHF)' },
  { code: 'LT', flag: 'lt', label: 'Lithuania (EUR €)' },
  { code: 'LU', flag: 'lu', label: 'Luxembourg (EUR €)' },
  { code: 'MO', flag: 'mo', label: 'Macao SAR (MOP P)' },
  { code: 'MG', flag: 'mg', label: 'Madagascar (USD $)' },
  { code: 'MW', flag: 'mw', label: 'Malawi (MWK MK)' },
  { code: 'MY', flag: 'my', label: 'Malaysia (MYR RM)' },
  { code: 'MV', flag: 'mv', label: 'Maldives (MVR MVR)' },
  { code: 'MT', flag: 'mt', label: 'Malta (EUR €)' },
  { code: 'MQ', flag: 'mq', label: 'Martinique (EUR €)' },
  { code: 'MR', flag: 'mr', label: 'Mauritania (USD $)' },
  { code: 'MU', flag: 'mu', label: 'Mauritius (MUR ₨)' },
  { code: 'YT', flag: 'yt', label: 'Mayotte (EUR €)' },
  { code: 'MX', flag: 'mx', label: 'Mexico (USD $)' },
  { code: 'MD', flag: 'md', label: 'Moldova (MDL L)' },
  { code: 'MC', flag: 'mc', label: 'Monaco (EUR €)' },
  { code: 'MN', flag: 'mn', label: 'Mongolia (MNT ₮)' },
  { code: 'ME', flag: 'me', label: 'Montenegro (EUR €)' },
  { code: 'MS', flag: 'ms', label: 'Montserrat (XCD $)' },
  { code: 'MA', flag: 'ma', label: 'Morocco (MAD د.م.)' },
  { code: 'MZ', flag: 'mz', label: 'Mozambique (USD $)' },
  { code: 'NA', flag: 'na', label: 'Namibia (USD $)' },
  { code: 'NR', flag: 'nr', label: 'Nauru (AUD $)' },
  { code: 'NP', flag: 'np', label: 'Nepal (NPR Rs.)' },
  { code: 'NL', flag: 'nl', label: 'Netherlands (EUR €)' },
  { code: 'NC', flag: 'nc', label: 'New Caledonia (XPF Fr)' },
  { code: 'NZ', flag: 'nz', label: 'New Zealand (NZD $)' },
  { code: 'NI', flag: 'ni', label: 'Nicaragua (NIO C$)' },
  { code: 'NG', flag: 'ng', label: 'Nigeria (NGN ₦)' },
  { code: 'NU', flag: 'nu', label: 'Niue (NZD $)' },
  { code: 'MK', flag: 'mk', label: 'North Macedonia (MKD ден)' },
  { code: 'NO', flag: 'no', label: 'Norway (USD $)' },
  { code: 'OM', flag: 'om', label: 'Oman (USD $)' },
  { code: 'PK', flag: 'pk', label: 'Pakistan (PKR ₨)' },
  { code: 'PA', flag: 'pa', label: 'Panama (USD $)' },
  { code: 'PG', flag: 'pg', label: 'Papua New Guinea (PGK K)' },
  { code: 'PY', flag: 'py', label: 'Paraguay (PYG ₲)' },
  { code: 'PE', flag: 'pe', label: 'Peru (PEN S/)' },
  { code: 'PH', flag: 'ph', label: 'Philippines (PHP ₱)' },
  { code: 'PL', flag: 'pl', label: 'Poland (PLN zł)' },
  { code: 'PT', flag: 'pt', label: 'Portugal (EUR €)' },
  { code: 'QA', flag: 'qa', label: 'Qatar (QAR ر.ق)' },
  { code: 'RE', flag: 're', label: 'Réunion (EUR €)' },
  { code: 'RO', flag: 'ro', label: 'Romania (RON Lei)' },
  { code: 'RW', flag: 'rw', label: 'Rwanda (RWF FRw)' },
  { code: 'WS', flag: 'ws', label: 'Samoa (WST T)' },
  { code: 'SM', flag: 'sm', label: 'San Marino (EUR €)' },
  { code: 'ST', flag: 'st', label: 'São Tomé & Príncipe (STD Db)' },
  { code: 'SA', flag: 'sa', label: 'Saudi Arabia (SAR ر.س)' },
  { code: 'SN', flag: 'sn', label: 'Senegal (XOF Fr)' },
  { code: 'RS', flag: 'rs', label: 'Serbia (RSD РСД)' },
  { code: 'SC', flag: 'sc', label: 'Seychelles (USD $)' },
  { code: 'SL', flag: 'sl', label: 'Sierra Leone (SLL Le)' },
  { code: 'SG', flag: 'sg', label: 'Singapore (SGD $)' },
  { code: 'SK', flag: 'sk', label: 'Slovakia (EUR €)' },
  { code: 'SI', flag: 'si', label: 'Slovenia (EUR €)' },
  { code: 'SB', flag: 'sb', label: 'Solomon Islands (SBD $)' },
  { code: 'ZA', flag: 'za', label: 'South Africa (USD $)' },
  { code: 'KR', flag: 'kr', label: 'South Korea (KRW ₩)' },
  { code: 'ES', flag: 'es', label: 'Spain (EUR €)' },
  { code: 'LK', flag: 'lk', label: 'Sri Lanka (LKR ₨)' },
  { code: 'BL', flag: 'bl', label: 'St. Barthélemy (EUR €)' },
  { code: 'KN', flag: 'kn', label: 'St. Kitts & Nevis (XCD $)' },
  { code: 'LC', flag: 'lc', label: 'St. Lucia (XCD $)' },
  { code: 'MF', flag: 'mf', label: 'St. Martin (EUR €)' },
  { code: 'VC', flag: 'vc', label: 'St. Vincent & Grenadines (XCD $)' },
  { code: 'SR', flag: 'sr', label: 'Suriname (USD $)' },
  { code: 'SE', flag: 'se', label: 'Sweden (SEK kr)' },
  { code: 'CH', flag: 'ch', label: 'Switzerland (CHF CHF)' },
  { code: 'TW', flag: 'tw', label: 'Taiwan (TWD $)' },
  { code: 'TZ', flag: 'tz', label: 'Tanzania (TZS Sh)' },
  { code: 'TH', flag: 'th', label: 'Thailand (THB ฿)' },
  { code: 'TL', flag: 'tl', label: 'Timor-Leste (USD $)' },
  { code: 'TG', flag: 'tg', label: 'Togo (XOF Fr)' },
  { code: 'TO', flag: 'to', label: 'Tonga (TOP T$)' },
  { code: 'TT', flag: 'tt', label: 'Trinidad & Tobago (TTD $)' },
  { code: 'TN', flag: 'tn', label: 'Tunisia (USD $)' },
  { code: 'TC', flag: 'tc', label: 'Turks & Caicos Islands (USD $)' },
  { code: 'TV', flag: 'tv', label: 'Tuvalu (AUD $)' },
  { code: 'UG', flag: 'ug', label: 'Uganda (UGX USh)' },
  { code: 'AE', flag: 'ae', label: 'United Arab Emirates (AED د.إ)' },
  { code: 'GB', flag: 'gb', label: 'United Kingdom (GBP £)' },
  { code: 'US', flag: 'us', label: 'United States (USD $)' },
  { code: 'UY', flag: 'uy', label: 'Uruguay (UYU $U)' },
  { code: 'UZ', flag: 'uz', label: 'Uzbekistan (UZS so\'m)' },
  { code: 'VU', flag: 'vu', label: 'Vanuatu (VUV Vt)' },
  { code: 'VN', flag: 'vn', label: 'Vietnam (VND ₫)' },
  { code: 'ZM', flag: 'zm', label: 'Zambia (USD $)' }
];
